### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by alixedi** [maxeler/FFT-2D#2]
cd APP/RunRules/Simulation/
make build

gives the following error:

[maxjcompiler] 1. ERROR in /home/azaidi/Documents/FFT-2D/APP/EngineCode/src/com/maxeler/applibrary/fft/lib/buffer/Transposer.maxj (at line 102)
[maxjcompiler] 	if (owner.getManager().getEngineParameters().getDFEModel().getDFEArchitecture() == DFEArchitecture.MAX4 ||
[maxjcompiler] 	                                                                                                   ^^^^
[maxjcompiler] MAX4 cannot be resolved or is not a field

**Comment by carmenfan** [comment]
Updated. The enum MAX4 is removed from trunk.

This worked for Maxcompiler 2014.2 which is the last compiler release. Note that the commited version will now break on 2014.2 as the MAX4_Coria enum does not exist in there.

**Comment by alixedi** [comment]
:+1:
